devices:
  - name: "room-a-sensor"
    enabled: true
    token: "device-token"
    labels:
      - name: "environment"
        enabled: true
        timestamp: "measuredAt"
        readonlyView:
          enabled: true
          token: "readonly-token"
      - name: "power"
        enabled: true
        readonlyView:
          enabled: false
